FROM python:3.13.7-alpine3.21

WORKDIR /app

RUN pip install grpcio grpcio-tools "fastapi[standard]"

COPY ./task_manager.proto .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. task_manager.proto

COPY ./fastapi_grpc.py .

RUN touch __init__.py

CMD ["uvicorn", "fastapi_grpc:app", "--host", "0.0.0.0"]
