services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile_servidor
    container_name: servidor
    ports:
      - 50051:50051

  cliente:
    build:
      context: .
      dockerfile: Dockerfile_cliente
    container_name: cliente
    depends_on:
      - servidor

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: fastapi
    ports:
      - 8000:8000
    depends_on:
      - servidor
