services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile_servidor
    container_name: servidor
    ports:
      - 50051:50051
    #network_mode: host

  cliente:
    build:
      context: .
      dockerfile: Dockerfile_cliente
    container_name: cliente
    depends_on:
      - servidor
    #network_mode: host
